'use client'
import { useState } from 'react'
import { Activity, CheckCircle2, Clock3, Search, XCircle } from 'lucide-react'
import { PageHeader } from '@/components/page-header'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { useNotificationStatus } from '@/hooks/use-notification-status'
export default function StatusPage(){const [id,setId]=useState('');const [query,setQuery]=useState('');const q=useNotificationStatus(query||undefined);const status=String((q.data as any)?.status??'Unknown');const terminal=['delivered','failed','cancelled','rejected'].includes(status.toLowerCase());return <div className="grid-bg min-h-full p-5 md:p-8"><div className="mx-auto max-w-[1100px]"><PageHeader eyebrow="Operations" title="Notification status" description="Inspect a notification by ID. Active requests are polled until a terminal delivery state."/><Card><CardContent className="p-5"><div className="flex gap-2"><Input value={id} onChange={e=>setId(e.target.value)} placeholder="Notification UUID" className="font-mono"/><Button onClick={()=>setQuery(id.trim())} disabled={!id.trim()}><Search size={16}/>Inspect</Button></div></CardContent></Card>{query&&<div className="mt-5 grid gap-5 md:grid-cols-[1fr_300px]"><Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Delivery state</CardTitle><Badge variant={terminal?(status.toLowerCase()==='delivered'?'success':'danger'):'warning'}>{status}</Badge></div></CardHeader><CardContent><div className="flex items-center gap-4 py-8"><StateIcon status={status}/><div><div className="font-mono text-xs text-muted-foreground">{query}</div><div className="mt-1 text-xl font-semibold">{status}</div><p className="mt-1 text-sm text-muted-foreground">{q.isFetching?'Refreshing from NotificationHub…':q.isError?'Unable to retrieve this notification.':'Latest server state'}</p></div></div></CardContent></Card><Card><CardHeader><CardTitle>Polling</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><Row icon={Activity} label="Auto refresh" value={terminal?'Stopped':'2.5s'}/><Row icon={Clock3} label="Source" value="GET /notifications/{id}"/><Row icon={CheckCircle2} label="Terminal" value={terminal?'Yes':'No'}/></CardContent></Card></div>}</div></div>}
function StateIcon({status}:{status:string}){const s=status.toLowerCase();if(s==='delivered')return <CheckCircle2 className="text-emerald-500" size={38}/>;if(['failed','rejected','cancelled'].includes(s))return <XCircle className="text-destructive" size={38}/>;return <Activity className="animate-pulse text-primary" size={38}/>} function Row({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="flex items-center justify-between"><span className="flex items-center gap-2 text-muted-foreground"><Icon size={15}/>{label}</span><span className="font-medium">{value}</span></div>}
