'use client'
import { useEffect, useMemo, useState } from 'react'
import { Eye, Loader2, Save, Trash2 } from 'lucide-react'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Select } from './ui/select'
import { Textarea } from './ui/textarea'
import { Badge } from './ui/badge'
import { Dialog } from './ui/dialog'
import { useDeleteTemplate, useSaveTemplate } from '@/hooks/use-templates'
import { templatesApi } from '@/lib/api/templates'
import { ApiError } from '@/lib/api/errors'
import type { TemplateDefinition } from '@/types/api'

export function TemplateEditor({ open, onOpenChange, initial, onSaved }: { open:boolean; onOpenChange:(v:boolean)=>void; initial?:TemplateDefinition; onSaved?:()=>void }) {
 const [form,setForm]=useState<TemplateDefinition>(initial ?? {key:'',channel:'email',locale:'fa-IR',subject:'',body:'',htmlBody:'',version:1,isActive:true})
 const [preview,setPreview]=useState(false); const [error,setError]=useState('')
 const save=useSaveTemplate(); const del=useDeleteTemplate()
 useEffect(()=>{setForm(initial ?? {key:'',channel:'email',locale:'fa-IR',subject:'',body:'',htmlBody:'',version:1,isActive:true});setError('')},[initial,open])
 const set=(k:keyof TemplateDefinition,v:any)=>setForm(x=>({...x,[k]:v}))
 const submit=async()=>{if(!form.key.trim()||!form.channel||!form.locale||!form.subject.trim()||!form.body.trim()){setError('Key, channel, locale, subject and body are required.');return}setError('');try{await save.mutateAsync(form);onSaved?.();onOpenChange(false)}catch(e){setError(e instanceof ApiError?e.message:'Unable to save template.')}}
 const remove=async()=>{if(!initial)return;if(!confirm(`Delete ${initial.key} / ${initial.channel} / ${initial.locale}?`))return;try{await del.mutateAsync({key:initial.key,channel:initial.channel,locale:initial.locale});onSaved?.();onOpenChange(false)}catch(e){setError(e instanceof ApiError?e.message:'Unable to delete template.')}}
 return <Dialog open={open} onOpenChange={onOpenChange} title={initial?'Edit template':'Create template'} description="Versioned content resolved by channel, locale and tenant."><div className="grid gap-5 p-5 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Field label="Template key" required><Input value={form.key} disabled={!!initial} onChange={e=>set('key',e.target.value)} placeholder="payment.success"/></Field><Field label="Channel" required><Select value={form.channel} onChange={e=>set('channel',e.target.value)}><option>email</option><option>sms</option><option>push</option><option>webhook</option></Select></Field><Field label="Locale" required><Input value={form.locale} onChange={e=>set('locale',e.target.value)} placeholder="fa-IR"/></Field></div><Field label="Subject" required><Input value={form.subject} onChange={e=>set('subject',e.target.value)} placeholder="Payment received · {{amount}}"/></Field><Field label="Body" required hint="Use {{variable}} placeholders"><Textarea value={form.body} onChange={e=>set('body',e.target.value)} className="min-h-48 font-mono text-xs" placeholder="Hello {{name}}, your payment of {{amount}} was successful."/></Field><Field label="HTML body"><Textarea value={form.htmlBody??''} onChange={e=>set('htmlBody',e.target.value)} className="min-h-40 font-mono text-xs" placeholder="<p>Hello {{name}}</p>"/></Field><div className="flex items-center justify-between rounded-xl border p-4"><div><div className="text-sm font-medium">Active version</div><div className="text-xs text-muted-foreground">Version {form.version ?? 1} is available for resolution.</div></div><input type="checkbox" checked={form.isActive!==false} onChange={e=>set('isActive',e.target.checked)} className="h-4 w-4 accent-primary"/></div>{error&&<div className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-xs text-destructive">{error}</div>}<div className="flex flex-wrap justify-between gap-2 border-t pt-4"><div>{initial&&<Button variant="ghost" className="text-destructive hover:text-destructive" onClick={remove} disabled={del.isPending}><Trash2 size={15}/>Delete</Button>}</div><div className="flex gap-2"><Button variant="outline" onClick={()=>setPreview(true)}><Eye size={15}/>Preview</Button><Button onClick={submit} disabled={save.isPending}>{save.isPending?<Loader2 className="animate-spin" size={15}/>:<Save size={15}/>}Save template</Button></div></div></div><PreviewPanel form={form}/></div><Dialog open={preview} onOpenChange={setPreview} title="Template preview" description="Client-side preview using sample data."><div className="p-5"><PreviewPanel form={form} large/></div></Dialog></Dialog>
}
function PreviewPanel({form,large}:{form:TemplateDefinition;large?:boolean}){const sample=useMemo(()=>({name:'Mohammad',amount:'1,250,000',reference:'PAY-29381'}),[]);const replace=(s:string)=>s.replace(/{{\s*(\w+)\s*}}/g,(_,k)=>String(sample[k as keyof typeof sample]??`{{${k}}}`));return <div className={large?'rounded-xl border':'rounded-2xl border bg-muted/20 p-4'}><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Live preview</span><Badge variant="outline">{form.channel} · {form.locale}</Badge></div><div className="rounded-xl bg-background p-5 shadow-sm"><div className="text-sm font-semibold">{replace(form.subject||'Untitled')}</div><div className="mt-4 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{replace(form.body||'No body')}</div></div></div>}
function Field({label,required,hint,children}:{label:string;required?:boolean;hint?:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="flex items-center gap-2 text-sm font-medium">{label}{required&&<span className="text-destructive">*</span>}{hint&&<span className="text-[10px] font-normal text-muted-foreground">{hint}</span>}</span>{children}</label>}
