<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Kernel\NotificationHub.Abstractions\NotificationHub.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Kavenegar" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  </Project>
