<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NotificationHub.Application\NotificationHub.Application.csproj" />
    <ProjectReference Include="..\NotificationHub.Domain\NotificationHub.Domain.csproj" />
    <ProjectReference Include="..\NotificationHub.Core\NotificationHub.Core.csproj" />
    <ProjectReference Include="..\..\Kernel\NotificationHub.Abstractions\NotificationHub.Abstractions.csproj" />
  </ItemGroup>
</Project>
