<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Kernel\NotificationHub.Abstractions\NotificationHub.Abstractions.csproj" />
    <ProjectReference Include="..\NotificationHub.Domain\NotificationHub.Domain.csproj" />
    <ProjectReference Include="..\NotificationHub.Core\NotificationHub.Core.csproj" />
  </ItemGroup>
</Project>
